// src/app/layout.server.tsx
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "RideSignals",
  description: "Generated by create next app",
};

export default function RootServerLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
