// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type GeoLocation struct {
	Lat float64 `json:"lat"`
	Lng float64 `json:"lng"`
}

type Mutation struct {
}

type Participant struct {
	UserID   string `json:"userId"`
	Role     string `json:"role"`
	JoinedAt string `json:"joinedAt"`
}

type Query struct {
}

type Ride struct {
	ID              string         `json:"id"`
	RideCode        string         `json:"rideCode"`
	Status          string         `json:"status"`
	CreatedAt       string         `json:"createdAt"`
	CreatedBy       string         `json:"createdBy"`
	EndedAt         *string        `json:"endedAt,omitempty"`
	Participants    []*Participant `json:"participants"`
	Settings        *RideSettings  `json:"settings"`
	Start           *GeoLocation   `json:"start"`
	Destination     *GeoLocation   `json:"destination"`
	StartName       string         `json:"startName"`
	DestinationName string         `json:"destinationName"`
}

type RideSettings struct {
	MaxRiders  int    `json:"maxRiders"`
	Visibility string `json:"visibility"`
}

type Signal struct {
	ID        string       `json:"id"`
	RideCode  string       `json:"rideCode"`
	FromUser  string       `json:"fromUser"`
	Type      string       `json:"type"`
	Timestamp string       `json:"timestamp"`
	Location  *GeoLocation `json:"location"`
}

type User struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Email       string `json:"email"`
	CreatedAt   string `json:"createdAt"`
	LastLoginAt string `json:"lastLoginAt"`
	IsActive    bool   `json:"isActive"`
}
