// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Mutation struct {
}

type PushSubscriptionInput struct {
	Endpoint       string                     `json:"endpoint"`
	Keys           *PushSubscriptionKeysInput `json:"keys"`
	ExpirationTime *string                    `json:"expirationTime,omitempty"`
}

type PushSubscriptionKeysInput struct {
	P256dh string `json:"p256dh"`
	Auth   string `json:"auth"`
}

type Query struct {
}

type UpdateUserInput struct {
	Name              *string                `json:"name,omitempty"`
	Email             *string                `json:"email,omitempty"`
	IsActive          *bool                  `json:"isActive,omitempty"`
	CurrentRide       *string                `json:"currentRide,omitempty"`
	Picture           *string                `json:"picture,omitempty"`
	PushSubscription  *PushSubscriptionInput `json:"pushSubscription,omitempty"`
	ClearSubscription *bool                  `json:"clearSubscription,omitempty"`
}
